In [1]:
grid = [[0] * 10] * 10

In [2]:
grid

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [3]:
def display_grid():
    for row in grid:
        print(row)

In [4]:
display_grid()

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [5]:
def display_grid():
    for row in grid:
        print(*row)

In [6]:
display_grid()

0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0


In [11]:
squares = {0: '\u2b1c', 1: '\u2b1b'}

In [8]:
'\u2b1c', '\u2b1b'

('⬜', '⬛')

In [9]:
def display_grid():
    for row in grid:
        print(''.join(squares[e] for e in row))

In [12]:
display_grid()

⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜


In [13]:
density = 0.2

In [14]:
from random import random

In [15]:
random(), random(), random()

(0.45480740028042954, 0.5017499195788141, 0.39485583212915387)

In [17]:
for i in range(10):
    for j in range(10):
        if random() < density:
            grid[i][j] = 1

In [18]:
display_grid()

⬛⬛⬛⬛⬜⬛⬛⬛⬛⬛
⬛⬛⬛⬛⬜⬛⬛⬛⬛⬛
⬛⬛⬛⬛⬜⬛⬛⬛⬛⬛
⬛⬛⬛⬛⬜⬛⬛⬛⬛⬛
⬛⬛⬛⬛⬜⬛⬛⬛⬛⬛
⬛⬛⬛⬛⬜⬛⬛⬛⬛⬛
⬛⬛⬛⬛⬜⬛⬛⬛⬛⬛
⬛⬛⬛⬛⬜⬛⬛⬛⬛⬛
⬛⬛⬛⬛⬜⬛⬛⬛⬛⬛
⬛⬛⬛⬛⬜⬛⬛⬛⬛⬛


In [19]:
L = [3, 3.14, [2, 4, 5], {3, 9}]

In [20]:
L[0], L[-1]

(3, {3, 9})

In [21]:
L = [[0] * 10] * 10

In [22]:
L

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [23]:
L[2][3] = 1

In [24]:
L

[[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0]]

In [25]:
L = [[0] * 10 for _ in range(10)]
L

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [26]:
L[2][3] = 1
L

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [28]:
L = [[0 for _ in range(10)] for _ in range(10)]

In [29]:
L

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [30]:
grid = [[0] * 10 for _ in range(10)]
for i in range(10):
    for j in range(10):
        if random() < density:
            grid[i][j] = 1
display_grid()

⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬛⬛⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬛⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬛⬜
⬜⬜⬜⬜⬜⬛⬛⬜⬜⬜
⬛⬜⬜⬜⬜⬜⬜⬜⬜⬛
⬜⬛⬛⬜⬛⬜⬜⬜⬜⬜
⬛⬜⬜⬜⬛⬜⬜⬜⬛⬜
⬜⬜⬛⬜⬜⬜⬛⬜⬜⬜
⬛⬜⬜⬜⬜⬜⬜⬜⬜⬜


In [31]:
grid = [[None] * 10 for _ in range(10)]
for i in range(10):
    for j in range(10):
        grid[i][j] = int(random() < density)
display_grid()

⬛⬜⬛⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬛⬜⬜⬜⬜⬜⬜
⬜⬜⬛⬜⬜⬜⬜⬜⬜⬜
⬛⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬛⬛⬜⬜⬜⬜⬛⬜
⬜⬜⬛⬛⬜⬜⬜⬜⬜⬛
⬜⬛⬜⬜⬜⬛⬜⬛⬜⬛
⬜⬛⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬛⬛⬜⬜⬛⬜⬜⬜⬜
⬛⬛⬜⬜⬜⬜⬜⬛⬛⬜


In [32]:
grid = [[int(random() < density) for _ in range(10)] for _ in range(10)]
display_grid()

⬛⬜⬜⬜⬛⬜⬜⬜⬜⬜
⬜⬜⬛⬜⬜⬜⬜⬜⬛⬜
⬛⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬛⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬛⬛⬜
⬜⬜⬜⬛⬜⬜⬜⬜⬜⬜
⬜⬜⬛⬛⬜⬜⬛⬜⬛⬜
⬜⬛⬜⬜⬜⬜⬜⬛⬜⬛
⬜⬜⬛⬜⬛⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬛⬜⬛


In [33]:
def evolve():
    new_grid = [[0] * 10 for _ in range(10)]
    nb_of_neighbours = 0
    for i in range(10):
        for j in range(10):
            # NW
            if i and j and grid[i - 1][j - 1]:
                nb_of_neighbours += 1
            # N
            if i and grid[i - 1][j]:
                nb_of_neighbours += 1
            # NE
            if i and j < 9 and grid[i - 1][j + 1]:
                nb_of_neighbours += 1
            # SW
            if i < 8 and j and grid[i + 1][j - 1]:
                nb_of_neighbours += 1
            # S
            if i < 8 and grid[i + 1][j]:
                nb_of_neighbours += 1
            # SE
            if i < 8 and j < 9 and grid[i + 1][j + 1]:
                nb_of_neighbours += 1
            # W
            if j and grid[i][j - 1]:
                nb_of_neighbours += 1
            # E
            if j < 9 and grid[i][j + 1]:
                nb_of_neighbours += 1
            if nb_of_neighbours == 3 or nb_of_neighbours == 2 and grid[i][j]:
                new_grid[i][j] = 1
    grid = new_grid

In [34]:
evolve()

UnboundLocalError: cannot access local variable 'grid' where it is not associated with a value

In [35]:
def evolve():
    global grid
    new_grid = [[0] * 10 for _ in range(10)]
    nb_of_neighbours = 0
    for i in range(10):
        for j in range(10):
            # NW
            if i and j and grid[i - 1][j - 1]:
                nb_of_neighbours += 1
            # N
            if i and grid[i - 1][j]:
                nb_of_neighbours += 1
            # NE
            if i and j < 9 and grid[i - 1][j + 1]:
                nb_of_neighbours += 1
            # SW
            if i < 8 and j and grid[i + 1][j - 1]:
                nb_of_neighbours += 1
            # S
            if i < 8 and grid[i + 1][j]:
                nb_of_neighbours += 1
            # SE
            if i < 8 and j < 9 and grid[i + 1][j + 1]:
                nb_of_neighbours += 1
            # W
            if j and grid[i][j - 1]:
                nb_of_neighbours += 1
            # E
            if j < 9 and grid[i][j + 1]:
                nb_of_neighbours += 1
            if nb_of_neighbours == 3 or nb_of_neighbours == 2 and grid[i][j]:
                new_grid[i][j] = 1
    grid = new_grid

In [36]:
display_grid()

⬛⬜⬜⬜⬛⬜⬜⬜⬜⬜
⬜⬜⬛⬜⬜⬜⬜⬜⬛⬜
⬛⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬛⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬛⬛⬜
⬜⬜⬜⬛⬜⬜⬜⬜⬜⬜
⬜⬜⬛⬛⬜⬜⬛⬜⬛⬜
⬜⬛⬜⬜⬜⬜⬜⬛⬜⬛
⬜⬜⬛⬜⬛⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬛⬜⬛


In [37]:
evolve()
display_grid()

⬜⬜⬛⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜


In [38]:
def evolve():
    global grid
    new_grid = [[0] * 10 for _ in range(10)]
    for i in range(10):
        for j in range(10):
            nb_of_neighbours = 0
            # NW
            if i and j and grid[i - 1][j - 1]:
                nb_of_neighbours += 1
            # N
            if i and grid[i - 1][j]:
                nb_of_neighbours += 1
            # NE
            if i and j < 9 and grid[i - 1][j + 1]:
                nb_of_neighbours += 1
            # SW
            if i < 8 and j and grid[i + 1][j - 1]:
                nb_of_neighbours += 1
            # S
            if i < 9 and grid[i + 1][j]:
                nb_of_neighbours += 1
            # SE
            if i < 9 and j < 9 and grid[i + 1][j + 1]:
                nb_of_neighbours += 1
            # W
            if j and grid[i][j - 1]:
                nb_of_neighbours += 1
            # E
            if j < 9 and grid[i][j + 1]:
                nb_of_neighbours += 1
            if nb_of_neighbours == 3 or nb_of_neighbours == 2 and grid[i][j]:
                new_grid[i][j] = 1
    grid = new_grid

In [41]:
density = 0.3
grid = [[int(random() < density) for _ in range(10)] for _ in range(10)]
display_grid()
print()
evolve()
display_grid()

⬜⬛⬜⬜⬛⬜⬜⬛⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬛⬛⬜
⬜⬜⬜⬛⬜⬛⬛⬜⬜⬜
⬜⬜⬜⬛⬜⬛⬛⬜⬜⬜
⬛⬜⬜⬛⬛⬜⬛⬜⬜⬜
⬜⬜⬜⬛⬛⬜⬜⬜⬜⬜
⬜⬜⬛⬜⬜⬛⬜⬜⬜⬜
⬜⬜⬛⬜⬜⬜⬜⬜⬜⬜
⬛⬜⬜⬜⬛⬜⬛⬜⬜⬜
⬛⬜⬜⬛⬜⬜⬜⬜⬜⬜

⬜⬜⬜⬜⬜⬜⬜⬛⬛⬜
⬜⬜⬜⬜⬛⬛⬜⬛⬛⬜
⬜⬜⬜⬜⬜⬛⬜⬜⬜⬜
⬜⬜⬛⬛⬜⬜⬜⬛⬜⬜
⬜⬜⬛⬜⬜⬜⬛⬜⬜⬜
⬜⬜⬛⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬛⬜⬛⬜⬜⬜⬜⬜
⬜⬛⬜⬛⬜⬛⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜


In [42]:
dim = 10

In [45]:
framed_grid = [[0] * (dim + 2) for _ in range(dim + 2)]

In [46]:
framed_grid

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [47]:
for i in range(1, dim + 1):
    for j in range(1, dim + 1):
        framed_grid[i][j] = int(random() < density)
framed_grid

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0],
 [0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0],
 [0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0],
 [0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [49]:
def display_within_framed_grid():
    for row in grid[1 : -1]:
        print(''.join(squares[e] for e in row[1 : -1]))

In [50]:
display_within_framed_grid()

⬜⬜⬜⬛⬛⬜⬛⬛
⬜⬜⬜⬜⬛⬜⬜⬜
⬜⬛⬛⬜⬜⬜⬛⬜
⬜⬛⬜⬜⬜⬛⬜⬜
⬜⬛⬜⬜⬜⬜⬜⬜
⬜⬛⬜⬛⬜⬜⬜⬜
⬛⬜⬛⬜⬛⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜


In [62]:
def framed_evolve():
    global grid
    new_grid = [[0] * 10 for _ in range(10)]
    for i in range(10):
        for j in range(10):
            nb_of_neighbours = sum(
                grid[i - 1][j - 1 : j + 2],
                grid[i + 1][j - 1 : j + 2],
                grid[i][j - 1],
                grid[i][j + 1])
            if nb_of_neighbours == 3 or nb_of_neighbours == 2 and grid[i][j]:
                new_grid[i][j] = 1
    grid = new_grid

In [51]:
row = [1, 2, 3, 4, 5, 6]

In [52]:
sum(row[1 : -1])

14

In [58]:
sum(2, 3, 4)

TypeError: sum() takes at most 2 arguments (3 given)

In [59]:
sum((2, 3, 4))

9

In [60]:
sum([1, 2], [3, 4], 5, 6)

TypeError: sum() takes at most 2 arguments (4 given)

In [61]:
x = [1, 2]
y = [3, 4]
sum((*x, *y, 5, 6))

21

In [63]:
framed_grid = [[0] * (dim + 2) for _ in range(dim + 2)]
for i in range(1, dim + 1):
    for j in range(1, dim + 1):
        framed_grid[i][j] = int(random() < density)
display_within_framed_grid()
print()
framed_evolve()
display_within_framed_grid()

⬜⬜⬜⬛⬛⬜⬛⬛
⬜⬜⬜⬜⬛⬜⬜⬜
⬜⬛⬛⬜⬜⬜⬛⬜
⬜⬛⬜⬜⬜⬛⬜⬜
⬜⬛⬜⬜⬜⬜⬜⬜
⬜⬛⬜⬛⬜⬜⬜⬜
⬛⬜⬛⬜⬛⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜



TypeError: sum() takes at most 2 arguments (4 given)

In [64]:
def framed_evolve():
    global grid
    new_grid = [[0] * 10 for _ in range(10)]
    for i in range(10):
        for j in range(10):
            nb_of_neighbours = sum(
                (*grid[i - 1][j - 1 : j + 2],
                *grid[i + 1][j - 1 : j + 2],
                grid[i][j - 1],
                grid[i][j + 1]))
            if nb_of_neighbours == 3 or nb_of_neighbours == 2 and grid[i][j]:
                new_grid[i][j] = 1
    grid = new_grid

In [65]:
framed_grid = [[0] * (dim + 2) for _ in range(dim + 2)]
for i in range(1, dim + 1):
    for j in range(1, dim + 1):
        framed_grid[i][j] = int(random() < density)
display_within_framed_grid()
print()
framed_evolve()
display_within_framed_grid()

⬜⬜⬜⬛⬛⬜⬛⬛
⬜⬜⬜⬜⬛⬜⬜⬜
⬜⬛⬛⬜⬜⬜⬛⬜
⬜⬛⬜⬜⬜⬛⬜⬜
⬜⬛⬜⬜⬜⬜⬜⬜
⬜⬛⬜⬛⬜⬜⬜⬜
⬛⬜⬛⬜⬛⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜



IndexError: list index out of range

In [72]:
def framed_evolve():
    global framed_grid
    new_grid = [[0] * (dim + 2) for _ in range(dim + 2)]
    for i in range(1, dim + 1):
        for j in range(1, dim + 1):
            nb_of_neighbours = sum(
                (*framed_grid[i - 1][j - 1 : j + 2],
                *framed_grid[i + 1][j - 1 : j + 2],
                framed_grid[i][j - 1],
                framed_grid[i][j + 1]))
            if nb_of_neighbours == 3 or nb_of_neighbours == 2 and framed_grid[i][j]:
                new_grid[i][j] = 1
    framed_grid = new_grid

In [74]:
framed_grid = [[0] * (dim + 2) for _ in range(dim + 2)]
for i in range(1, dim + 1):
    for j in range(1, dim + 1):
        framed_grid[i][j] = int(random() < density)
display_within_framed_grid()
print()
framed_evolve()
display_within_framed_grid()

⬜⬜⬜⬛⬛⬜⬛⬛
⬜⬜⬜⬜⬛⬜⬜⬜
⬜⬛⬛⬜⬜⬜⬛⬜
⬜⬛⬜⬜⬜⬛⬜⬜
⬜⬛⬜⬜⬜⬜⬜⬜
⬜⬛⬜⬛⬜⬜⬜⬜
⬛⬜⬛⬜⬛⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜

⬜⬜⬜⬛⬛⬜⬛⬛
⬜⬜⬜⬜⬛⬜⬜⬜
⬜⬛⬛⬜⬜⬜⬛⬜
⬜⬛⬜⬜⬜⬛⬜⬜
⬜⬛⬜⬜⬜⬜⬜⬜
⬜⬛⬜⬛⬜⬜⬜⬜
⬛⬜⬛⬜⬛⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜


In [75]:
import numpy as np

In [76]:
np.array([1, 4, 6, 7])

array([1, 4, 6, 7])

In [77]:
A = np.array([1, 4, 6, 7])
A[1]

np.int64(4)

In [78]:
A = np.arange(1, 9)
A

array([1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
A.reshape(2, 4)
A.reshape(4, 2)
A.reshape(2, 2, 2)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [80]:
A.reshape(2, 4)[1, 2] = 70

In [81]:
A

array([ 1,  2,  3,  4,  5,  6, 70,  8])

In [82]:
A.reshape(2, 2, 2)[1, 0, 1] = 100

In [83]:
A.reshape(4, 2)

array([[  1,   2],
       [  3,   4],
       [  5, 100],
       [ 70,   8]])

In [84]:
L = np.array(range(16)).reshape(2, 8)

L
L[1, 2]
L[1, :]
L[1 : 2, :]
L[:, 3]
L[:, 3 : 4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

np.int64(10)

array([ 8,  9, 10, 11, 12, 13, 14, 15])

array([[ 8,  9, 10, 11, 12, 13, 14, 15]])

array([ 3, 11])

array([[ 3],
       [11]])

In [ ]:
[[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]]