In [2]:
from random import random

import numpy as np

In [22]:
dim = 10
density = 0.3
squares = {0: '\u2b1c', 1: '\u2b1b'}

In [26]:
def display_within_framed_grid():
    for row in framed_grid[1 : -1]:
        print(''.join(squares[e] for e in row[1 : -1]))

In [33]:
def framed_evolve():
    global framed_grid
    new_grid = np.zeros((dim + 2, dim + 2), int)
    N = framed_grid[: -2, 1 : -1]
    S = framed_grid[2 :, 1 : -1]    
    E = framed_grid[1 : -1, 2 :]
    W = framed_grid[1 : -1, : -2]
    NE = framed_grid[: -2, 2 :]
    NW = framed_grid[: -2, : - 2]
    SE = framed_grid[2 :, 2 :]
    SW = framed_grid[2 :, : - 2]
    nb_of_neighbours = N + S + E + W + NE + NW + SE + SW
    new_grid[1 : -1, 1 : -1] = nb_of_neighbours
    framed_grid = np.logical_or(new_grid == 3,
                                np.logical_and(new_grid == 2, framed_grid == 1)
                               )

In [34]:
# framed_grid = [[0] * (dim + 2) for _ in range(dim + 2)]
framed_grid = np.zeros((dim + 2, dim + 2), int)
for i in range(1, dim + 1):
    for j in range(1, dim + 1):
        framed_grid[i, j] = int(random() < density)
display_within_framed_grid()
print()
framed_evolve()
display_within_framed_grid()

⬜⬜⬜⬜⬛⬜⬜⬜⬛⬜
⬜⬜⬜⬜⬜⬜⬜⬛⬜⬜
⬜⬜⬜⬛⬜⬜⬜⬜⬜⬛
⬜⬛⬜⬜⬜⬜⬜⬜⬛⬜
⬜⬜⬛⬜⬜⬛⬜⬜⬛⬜
⬜⬜⬜⬜⬜⬜⬜⬛⬜⬜
⬛⬜⬜⬜⬜⬛⬜⬛⬛⬜
⬜⬛⬜⬛⬜⬛⬛⬜⬜⬛
⬜⬜⬜⬛⬜⬜⬛⬛⬜⬜
⬜⬜⬛⬜⬜⬜⬜⬜⬛⬛

⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬛⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬛⬜
⬜⬜⬛⬜⬜⬜⬜⬜⬛⬛
⬜⬜⬜⬜⬜⬜⬜⬛⬛⬜
⬜⬜⬜⬜⬜⬜⬜⬛⬜⬜
⬜⬜⬜⬜⬛⬛⬜⬛⬛⬜
⬜⬜⬛⬜⬜⬛⬜⬜⬜⬜
⬜⬜⬜⬛⬛⬛⬛⬛⬜⬛
⬜⬜⬜⬜⬜⬜⬜⬛⬛⬜


In [3]:
L = np.array(range(16)).reshape(2, 2, 4)

L
L[1, 0, 2]
L[1, 1, 1 :]
L[1, :, 1 : 3]
L[0 : 1, 0 : 1, 1 : 3]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

np.int64(10)

array([13, 14, 15])

array([[ 9, 10],
       [13, 14]])

array([[[1, 2]]])

In [6]:
L = np.arange(1, 5).reshape(2, 2)
L

array([[1, 2],
       [3, 4]])

In [7]:
L1 = np.arange(10, 50, 10).reshape(2, 2)
L1

array([[10, 20],
       [30, 40]])

In [8]:
L + L1

array([[11, 22],
       [33, 44]])

In [9]:
L1 = np.array([10, 20])
L1

array([10, 20])

In [10]:
L
L1

array([[1, 2],
       [3, 4]])

array([10, 20])

In [11]:
L + L1

array([[11, 22],
       [13, 24]])

In [12]:
L1 = np.array([10, 20]).reshape(2, 1)
L1

array([[10],
       [20]])

In [13]:
L + L1

array([[11, 12],
       [23, 24]])

In [14]:
L + 10

array([[11, 12],
       [13, 14]])

In [15]:
L * 10

array([[10, 20],
       [30, 40]])

In [16]:
L1 = np.arange(10, 50, 10).reshape(2, 2)
L
L1

array([[1, 2],
       [3, 4]])

array([[10, 20],
       [30, 40]])

In [17]:
L @ L1

array([[ 70, 100],
       [150, 220]])

In [18]:
L1 = np.array([0, 2, 1, 0]).reshape(2, 2)
L2 = np.array([0, 0, 3, 4]).reshape(2, 2)
L1
L2

array([[0, 2],
       [1, 0]])

array([[0, 0],
       [3, 4]])

In [19]:
np.logical_and(L1, L2)

array([[False, False],
       [ True, False]])

In [20]:
np.logical_and(L1, L2).astype(int)

array([[0, 0],
       [1, 0]])

In [21]:
np.logical_or(L1, L2).astype(int)

array([[0, 1],
       [1, 1]])

In [31]:
np.zeros((dim + 2, dim + 2), int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [32]:
L = np.arange(1, 5).reshape(2, 2)
L
L == 2

array([[1, 2],
       [3, 4]])

array([[False,  True],
       [False, False]])

In [36]:
def f():
    yield 0
    yield 1

In [37]:
f()

<generator object f at 0x108e42e50>

In [41]:
I = f()

In [42]:
next(I), next(I)

(0, 1)

In [44]:
def f(x):
    while True:
        yield x
        if x % 2 == 0:
            x //= 2
        else:
            x = x * 3 + 1

In [46]:
I = f(100)

In [48]:
I = f(100)
[next(I) for _ in range(30)]

[100,
 50,
 25,
 76,
 38,
 19,
 58,
 29,
 88,
 44,
 22,
 11,
 34,
 17,
 52,
 26,
 13,
 40,
 20,
 10,
 5,
 16,
 8,
 4,
 2,
 1,
 4,
 2,
 1,
 4]

In [49]:
def f():
    x = 0
    while True:
        yield x
        x += 1

In [50]:
I = f()

In [51]:
next(I), next(I), next(I)

(0, 1, 2)

In [52]:
lambda x: (x + a / x) / 2

<function __main__.<lambda>(x)>

In [54]:
(lambda x: (x + 2 / x) / 2)(3)

1.8333333333333333

In [55]:
(lambda x: (x + 2 / x) / 2)(1.8333333333333333)

1.4621212121212122

In [56]:
(lambda x: (x + 2 / x) / 2)(1.4621212121212122)

1.414998429894803

In [57]:
iterate = lambda x: (x + a / x) / 2

In [58]:
def f():
    yield 0
    return
    yield 1

In [59]:
I = f()

In [60]:
next(I)

0

In [61]:
next(I)

StopIteration: 